import IBigChar from "./IBigChar";

export default class Big1 implements IBigChar {
  print (): string {
    return `
      .....##.....
      ..#####.....
      .....##.....
      .....##.....
      .....##.....
      ..########..
    `;
  }
}
